default:
    num_epochs: 3000
    hidden_size: 128
    num_layers: 2
    criterion: CrossEntropyLoss
    optimizer: Adam
    lr: 5e-3

analysis:
    proc_1: # alternate hidden_size
        set_1: 
            num_epochs: 3000
            hidden_size: 8 # low value to check for the compression of character-level information 
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-3
        set_2: 
            num_epochs: 3000
            hidden_size: 128
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-3
        set_3: 
            num_epochs: 3000
            hidden_size: 256 # high value to check for sparsity of character-level information (limited due to low-computational resources)
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-3
    proc_2: # alternate num_layers
        set_1: 
            num_epochs: 3000
            hidden_size: 128
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-3
        set_2: 
            num_epochs: 3000
            hidden_size: 128
            num_layers: 5
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-3
        set_3: 
            num_epochs: 3000
            hidden_size: 128
            num_layers: 10
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-3
    proc_3: # alternate optimizer
        set_1:
            num_epochs: 3000
            hidden_size: 128
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-3
        set_2:
            num_epochs: 3000
            hidden_size: 128
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: AdamW
            lr: 5e-3
        set_3:
            num_epochs: 3000
            hidden_size: 128
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: RMSprop
            lr: 5e-3
    proc_4: # alternate learning rate
        set_1:
            num_epochs: 3000
            hidden_size: 128
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-2
        set_2:
            num_epochs: 3000
            hidden_size: 128
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-3
        set_3:
            num_epochs: 3000
            hidden_size: 128
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-4
        set_4: 
            num_epochs: 3000
            hidden_size: 128
            num_layers: 2
            criterion: CrossEntropyLoss
            optimizer: Adam
            lr: 5e-5    

plot_Train_loss:
    set_1: 
        num_epochs: 3000
        hidden_size: 128
        num_layers: 2
        criterion: CrossEntropyLoss
        optimizer: Adam
        lr: 1e-1
    set_2: 
        num_epochs: 3000
        hidden_size: 128
        num_layers: 2
        criterion: CrossEntropyLoss
        optimizer: Adam
        lr: 5e-2
    set_3: 
        num_epochs: 3000
        hidden_size: 128
        num_layers: 2
        criterion: CrossEntropyLoss
        optimizer: Adam
        lr: 1e-2
    set_4: 
        num_epochs: 3000
        hidden_size: 128
        num_layers: 2
        criterion: CrossEntropyLoss
        optimizer: Adam
        lr: 5e-3
    set_5: 
        num_epochs: 3000
        hidden_size: 128
        num_layers: 2
        criterion: CrossEntropyLoss
        optimizer: Adam
        lr: 1e-3
    set_6: 
        num_epochs: 3000
        hidden_size: 128
        num_layers: 2
        criterion: CrossEntropyLoss
        optimizer: Adam
        lr: 5e-4
    set_7: 
        num_epochs: 3000
        hidden_size: 128
        num_layers: 2
        criterion: CrossEntropyLoss
        optimizer: Adam
        lr: 1e-4
    set_8: 
        num_epochs: 3000
        hidden_size: 128
        num_layers: 2
        criterion: CrossEntropyLoss
        optimizer: Adam
        lr: 5e-5